[[permission]]
identifier = "app-core"
description = "Allows core application commands"
commands.allow = [
    "open_directory",
    "save_env_to_system",
    "get_platform_info",
    "search_files",
    "ide_open_window",
    "list_files",
    "server_start",
    "server_stop",
    "server_get_status",
    "watch_dir",
    "unwatch_dir",
    "shell_execute"
]
