export const providers = [
  {
    provider_id: 'claude',
    provider_name: 'Claude',
    is_enabled: true,
    website: 'https://claude.ai/',
    is_search: false,
    is_upload: true,
    auth_method: ['basic', 'google'],
    models: [
      {
        id: 'claude-sonnet-4-5-20250929',
        name: 'Claude Sonnet 4.5',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: true,
      },
      {
        id: 'claude-haiku-4-5-20251001',
        name: 'Claude Haiku 4.5',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: true,
      },
      {
        id: 'claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: true,
      },
    ],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'deepseek',
    provider_name: 'DeepSeek',
    is_enabled: true,
    website: 'https://deepseek.com',
    is_search: true,
    is_upload: true,
    is_pausable: true,
    auth_method: ['basic', 'google'],
    models: [
      {
        id: 'deepseek-instant',
        name: 'DeepSeek Instant',
        is_thinking: true,
        context_length: null,
        is_search: true,
        is_upload: true,
      },
      {
        id: 'deepseek-expert',
        name: 'DeepSeek Expert',
        is_thinking: true,
        context_length: null,
        is_search: true,
        is_upload: true,
      },
    ],
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'gemini',
    provider_name: 'Gemini',
    is_enabled: false,
    website: 'https://gemini.google.com/',
    is_search: false,
    is_upload: false,
    auth_method: ['google'],
    models: [
      {
        id: '0',
        name: 'Gemini 3.0 Flash',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
      {
        id: '1',
        name: 'Gemini 3.0 Flash Thinking',
        is_thinking: true,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
      {
        id: '2',
        name: 'Gemini 3.0 Pro',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
    ],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'groq',
    provider_name: 'Groq',
    is_enabled: true,
    website: 'https://groq.com',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'huggingchat',
    provider_name: 'HuggingChat',
    is_enabled: true,
    website: 'https://huggingface.co/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'kimi',
    provider_name: 'Kimi',
    is_enabled: false,
    website: 'https://www.kimi.com/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'lmarena',
    provider_name: 'LMArena',
    is_enabled: false,
    website: 'https://lmarena.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'mistral',
    provider_name: 'Mistral',
    is_enabled: true,
    website: 'https://mistral.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'perplexity',
    provider_name: 'Perplexity',
    is_enabled: true,
    website: 'https://www.perplexity.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'qwen',
    provider_name: 'Qwen',
    is_enabled: true,
    website: 'https://qwenlm.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic', 'google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'stepfun',
    provider_name: 'StepFun',
    is_enabled: false,
    website: 'https://stepfun.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'cerebras',
    provider_name: 'Cerebras',
    is_enabled: false,
    website: 'https://cerebras.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic', 'google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'cerebras-cloud',
    provider_name: 'Cerebras Cloud',
    is_enabled: true,
    website: 'https://cloud.cerebras.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic', 'google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'googlestudio',
    provider_name: 'Google Studio',
    is_enabled: false,
    website: 'https://aistudio.google.com/',
    is_search: false,
    is_upload: true,
    auth_method: ['google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'z',
    provider_name: 'Z',
    is_enabled: true,
    website: 'https://chat.z.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['google', 'basic'],
    is_pausable: false,
    connection_mode: 'headless_browser',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'qwen-cli',
    provider_name: 'Qwen Coder CLI',
    is_enabled: true,
    website: 'https://qwenlm.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    models: [
      {
        id: 'coder-model',
        name: 'Coder Model',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
    ],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'concurrent',
  },
  {
    provider_id: 'gemini-cli',
    provider_name: 'Gemini CLI',
    is_enabled: true,
    website: 'https://gemini.google.com/',
    is_search: false,
    is_upload: false,
    auth_method: ['google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'concurrent',
  },
  {
    provider_id: 'iflow-cli',
    provider_name: 'iFlow CLI',
    is_enabled: false,
    website: 'https://iflow.ai/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'codex-cli',
    provider_name: 'Codex CLI',
    is_enabled: true,
    website: 'https://google.com/',
    is_search: false,
    is_upload: false,
    auth_method: ['google', 'basic'],
    models: [
      {
        id: 'gpt-5.3-codex',
        name: 'GPT-5.3 Codex',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
      {
        id: 'gpt-5.2-codex',
        name: 'GPT-5.2 Codex',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
      {
        id: 'gpt-5.1-codex-max',
        name: 'GPT-5.1 Codex Max',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
      {
        id: 'gpt-5.2',
        name: 'GPT-5.2',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
      {
        id: 'gpt-5.1-codex-mini',
        name: 'GPT-5.1 Codex Mini',
        is_thinking: false,
        context_length: null,
        is_search: false,
        is_upload: false,
      },
    ],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'concurrent',
  },
  {
    provider_id: 'kiro-cli',
    provider_name: 'Kiro CLI',
    is_enabled: true,
    website: 'https://kiro.dev/',
    is_search: false,
    is_upload: false,
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'concurrent',
  },
];
