export const providers = [
  {
    provider_id: 'claude',
    provider_name: 'Claude',
    is_enabled: true,
    website_url: 'https://claude.ai/',
    auth_method: ['basic', 'google'],
    models: [
      {
        id: 'claude-sonnet-4-5-20250929',
        name: 'Claude Sonnet 4.5',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: true,
        is_video_upload: false,
        description: 'Anthropic\'s Claude Sonnet 4.5 - Balanced performance for everyday tasks with strong reasoning and image understanding',
      },
      {
        id: 'claude-haiku-4-5-20251001',
        name: 'Claude Haiku 4.5',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: true,
        is_video_upload: false,
        description: 'Anthropic\'s Claude Haiku 4.5 - Fast, compact model optimized for low-latency responses and efficient processing',
      },
      {
        id: 'claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: true,
        is_video_upload: false,
        description: 'Anthropic\'s Claude Sonnet 4.6 - Enhanced version with improved accuracy and broader knowledge base',
      },
    ],
    is_pausable: false,
  },
  {
    provider_id: 'deepseek',
    provider_name: 'DeepSeek',
    is_enabled: true,
    website_url: 'https://deepseek.com',
    is_pausable: true,
    auth_method: ['basic', 'google'],
    models: [
      {
        id: 'deepseek-instant',
        name: 'DeepSeek Instant',
        is_thinking: true,
        max_context_length: null,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description: 'DeepSeek Instant - Fast responses with web search capability and image understanding, supports thinking mode',
      },
      {
        id: 'deepseek-expert',
        name: 'DeepSeek Expert',
        is_thinking: true,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'DeepSeek Expert - Specialized reasoning model with deep analytical capabilities, no search or upload support',
      },
    ],
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'gemini',
    provider_name: 'Gemini',
    is_enabled: true,
    website_url: 'https://gemini.google.com/',
    auth_method: ['google'],
    models: [
      {
        id: 'gemini-3.5-flash',
        name: 'Gemini 3.5 Flash',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'Google Gemini 3.5 Flash - Fast and efficient model for everyday tasks, optimized for quick responses',
      },
      {
        id: 'gemini-3.5-flash-thinking',
        name: 'Gemini 3.5 Flash Thinking',
        is_thinking: true,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'Google Gemini 3.5 Flash Thinking - Enhanced reasoning with step-by-step thinking process for complex problems',
      },
      {
        id: 'gemini-3.5-flash-thinking-lite',
        name: 'Gemini 3.5 Flash Thinking Lite',
        is_thinking: true,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'Google Gemini 3.5 Flash Thinking Lite - Lightweight version with thinking mode, balances speed and depth',
      },
      {
        id: 'gemini-3.1-pro',
        name: 'Gemini 3.1 Pro',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'Google Gemini 3.1 Pro - Professional-grade model with advanced capabilities for complex tasks',
      },
      {
        id: 'gemini-auto',
        name: 'Gemini Auto',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'Google Gemini Auto - Automatically selects optimal model based on task complexity and requirements',
      },
      {
        id: 'gemini-flash-lite',
        name: 'Gemini Flash Lite',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'Google Gemini Flash Lite - Ultra-lightweight model for resource-constrained environments and high throughput',
      },
    ],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'groq',
    provider_name: 'Groq',
    is_enabled: true,
    website_url: 'https://groq.com',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'huggingchat',
    provider_name: 'HuggingChat',
    is_enabled: true,
    website_url: 'https://huggingface.co/',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'kimi',
    provider_name: 'Kimi',
    is_enabled: false,
    website_url: 'https://www.kimi.com/',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'lmarena',
    provider_name: 'LMArena',
    is_enabled: false,
    website_url: 'https://lmarena.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'mistral',
    provider_name: 'Mistral',
    is_enabled: true,
    website_url: 'https://mistral.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'perplexity',
    provider_name: 'Perplexity',
    is_enabled: true,
    website_url: 'https://www.perplexity.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'qwen',
    provider_name: 'Qwen',
    is_enabled: true,
    website_url: 'https://qwenlm.ai/',
    auth_method: ['basic', 'google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'stepfun',
    provider_name: 'StepFun',
    is_enabled: false,
    website_url: 'https://stepfun.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'cerebras',
    provider_name: 'Cerebras',
    is_enabled: false,
    website_url: 'https://cerebras.ai/',
    auth_method: ['basic', 'google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'cerebras-cloud',
    provider_name: 'Cerebras Cloud',
    is_enabled: true,
    website_url: 'https://cloud.cerebras.ai/',
    auth_method: ['basic', 'google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'googlestudio',
    provider_name: 'Google Studio',
    is_enabled: false,
    website_url: 'https://aistudio.google.com/',
    auth_method: ['google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'z',
    provider_name: 'Z',
    is_enabled: true,
    website_url: 'https://chat.z.ai/',
    auth_method: ['google', 'basic'],
    is_pausable: false,
    connection_mode: 'headless_browser',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'qwen-cli',
    provider_name: 'Qwen Coder CLI',
    is_enabled: true,
    website_url: 'https://qwenlm.ai/',
    auth_method: ['basic'],
    models: [
      {
        id: 'coder-model',
        name: 'Coder Model',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'Qwen Coder Model - Specialized for code generation, debugging, and programming assistance',
      },
    ],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'concurrent',
  },
  {
    provider_id: 'gemini-cli',
    provider_name: 'Gemini CLI',
    is_enabled: true,
    website_url: 'https://gemini.google.com/',
    auth_method: ['google'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'concurrent',
  },
  {
    provider_id: 'iflow-cli',
    provider_name: 'iFlow CLI',
    is_enabled: false,
    website_url: 'https://iflow.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'sequential',
  },
  {
    provider_id: 'codex-cli',
    provider_name: 'Codex CLI',
    is_enabled: true,
    website_url: 'https://google.com/',
    auth_method: ['google', 'basic'],
    models: [
      {
        id: 'gpt-5.3-codex',
        name: 'GPT-5.3 Codex',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'OpenAI GPT-5.3 Codex - Advanced coding model with extensive programming knowledge and problem-solving',
      },
      {
        id: 'gpt-5.2-codex',
        name: 'GPT-5.2 Codex',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'OpenAI GPT-5.2 Codex - Powerful code generation model with strong reasoning for complex algorithms',
      },
      {
        id: 'gpt-5.1-codex-max',
        name: 'GPT-5.1 Codex Max',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'OpenAI GPT-5.1 Codex Max - Maximum capacity coding model for large-scale software development',
      },
      {
        id: 'gpt-5.2',
        name: 'GPT-5.2',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'OpenAI GPT-5.2 - General purpose model with balanced capabilities for diverse tasks',
      },
      {
        id: 'gpt-5.1-codex-mini',
        name: 'GPT-5.1 Codex Mini',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description: 'OpenAI GPT-5.1 Codex Mini - Compact coding assistant for quick iterations and lightweight tasks',
      },
    ],
    is_pausable: false,
    connection_mode: 'https_spoofing',
    concurrency_mode: 'concurrent',
  },
];
